name: Deploy Node Application

on: 
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or the version your project uses

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t integrationninjas/nodejs-app .

      - name: Publish Image to Docker Hub
        run: docker push integrationninjas/nodejs-app:latest
 
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull integrationninjas/nodejs-app:latest

      - name: Delete old container
        run: |
          if [ "$(docker ps -aq -f name=nodejs-app-container)" ]; then
            docker rm -f nodejs-app-container
          fi

      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} integrationninjas/nodejs-app:latest
